# =============================================
# Конфигурационный файл парсера новостей
# Формат: YAML (UTF-8)
# =============================================

common:
  # -------------------------------------------
  # Системные параметры (неизменяемые настройки)
  # -------------------------------------------
  system:
    # Пути хранения данных
    raw_data_dir: "data/raw"           # Директория для сырых JSON-данных
    enriched_data_dir: "data/enriched" # Для обработанных данных
    logs_dir: "logs"                   # Каталог логов (парсинг-ошибки)

    # Настройки запросов
    request_timeout: 10                            # Таймаут HTTP-запросов (в секундах)
    max_retries: 3                                 # Максимальное количество попыток при ошибках сети

    # Временные параметры
    lookback_hours: 12                             # Период сбора новостей (от текущего момента)
    parser_timezone: "Europe/Moscow"               # Часовой пояс для внутренних операций парсера
                                                   # Формат: IANA Time Zone (https://data.iana.org/time-zones)
                                                   # Проверить: import pytz; print(pytz.all_timezones)

  # -------------------------------------------
  # Параметры по умолчанию (можно переопределять)
  # -------------------------------------------
  defaults:
    max_news: 10                                   # Лимит новостей на RSS-канал
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" # User-Agent для HTTP-запросов


# =============================================
# Настройки источников
# =============================================
sources:
  # -------------------------------------------
  # РИА Новости (https://ria.ru)
  # -------------------------------------------
  ria.ru:
    # Префикс для именования файлов
    raw_prefix: "raw_ria"                          # Формат: {prefix}_YYYYMMDD_HHMM.json
    
    # RSS-каналы
    rss_channels:
      # Главная лента
      main:
        url: "https://ria.ru/export/rss2/index.xml" # URL RSS-ленты
        category: "general"                         # Категория для классификации
      
      # Политические новости
      politics:
        url: "https://ria.ru/export/rss2/politics/index.xml"
        category: "politics"
        max_news: 15                               # Локальное переопределение лимита

  # -------------------------------------------
  # Lenta.ru (https://lenta.ru)
  # -------------------------------------------
  lenta.ru:
    raw_prefix: "raw_lenta"                        # Префикс файлов
    
    rss_channels:
      # Топ новостей
      top:
        url: "https://lenta.ru/rss/news"
        category: "general"
      
      # Мировые новости
      world:
        url: "https://lenta.ru/rss/news/world"
        category: "world"
        max_news: 8                                # Свой лимит для канала